name: PAM Obtain Demo

on: # 触发时机
  push:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]

jobs:
  openshift_demo:
    runs-on: [self-hosted] # 自建环境
    name: openshift
    steps:
      # step1: 通过 Action, 使用 PAM 查询密码
      - id: step1
        name: Import pam-obtain using username password obtain Action
        # heyh-bit/pam-obtain@v96
        uses: heyh-bit/pam-obtain@v96
        # pam-obtain Action Arguments
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "ip address"
          credential: ${{ secrets.PAM_TOKEN }}
      # step2: 通过 env.password 使用查询的密码
      - id: step2
        name: 修改 openshift 的 secret 值
        run: >
          oc create secret generic hello-world2
          --from-literal=username=hello
          --from-literal=pwd=${{ env.password }}
          --dry-run=client -o yaml -n default | oc replace -f -
