name: PAM Obtain Demo

on: # 触发时机
  push:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]

jobs:
  mysql-update:
    runs-on: [self-hosted]
    name: mysql
    steps:
      # step1: 通过 Action, 使用 PAM 查询密码
      - id: step1
        name: username password obtain
        uses: shterm/pam-obtain@v1
        # pam-obtain Action Arguments
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      # step2: 通过 env.password 使用查询的密码
      - id: step2
        name: mysql update
        run: >
          podman run registry.cn-hangzhou.aliyuncs.com/hos_test/mysql-client 
          mysql -u root
          -p${{ env.password }}
          -h "8.221.143.170"
          -P 3306 
          -e "show databases;"
