name: Build and Run Container Demo
on:
  push:
  issue_comment:
    types: [created, deleted]
jobs:
  blank-user-passwd-obtain:
    runs-on: [self-hosted]
    steps:
      - id: step1
        name: hello world
        run: |
          ip addr; echo "heyh success" >> /opt/out.out
