name: action.yml demo
 
on:
  issue_comment:
    types: [created, deleted]
  issues:
    types: [opened, edited, milestoned]
       
jobs:
  mysql-update:
    runs-on: [self-hosted]
    name: mysql
    steps:
      - id: step1
        name: username password obtain
        uses: shterm/pam-obtain@v1
        with:
          app-id: "test"
          user-name: "root"
          asset-name: "resource"
          connect-host: "10.13.1.2"
          credential: ${{ secrets.PAM_TOKEN }}
      - id: step2
        name: MySQL 更新
        run: >
          docker run registry.cn-hangzhou.aliyuncs.com/hos_test/mysql-client
          mysql -u root
          -p${{ env.password }}
          -h "8.221.143.170"
          -P 3306
          -e "show databases;"
